name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout so job can access repo
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v5.0.0
        with: 
          python-version: 3.11

      - name: bandit install
        run: pip install bandit

      - name: run bandit command
        run: |
          output=$(bandit -r . -ll -ii -f custom --msg-template "{severity}")
          echo "$output"  # Print Bandit output for reference
          # Check if HIGH severity is found
          if grep -q "HIGH" <<< "$output"; then
            echo "Blocked: HIGH severity vulnerability found by Bandit."

          fi
            
          
        
