name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout so job can access repo
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v5.0.0
        with: 
          python-version: 3.11

      - name: bandit install
        run: |
          pip install bandit
          pip install requests
          
      - name: run bandit command
        run: |
          bandit -r . -ll -ii -f custom --msg-template "{severity}" --exit-zero -o out.txt
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          python3 parser.py   

      - name: automerge
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
