name: CI
on: [push]
#   pull_request:
#     branches: 
#       - main
#     types: [closed]

jobs:
  build2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout so job can access repo
        uses: actions/checkout@v3

      - name: install NodeJS
        uses: actions/setup-node@v4.0.2

      - name: install retire
        run: npm install -g retire
        run: retire --help
