name: CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout so job can access repo
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v5.0.0
        with: 
          python-version: 3.11

      - name: bandit install
        run: |
          pip install bandit
          pip install requests
          
      - name: run bandit command
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_PR_NUMBER: "${{ github.event.number }}"
        run: |
          bandit -r . -ll -ii -f custom --msg-template "{severity}" --exit-zero -o out.txt
          python3 parser.py   

      - name: Merge pull request
        run: |
          GITHUB_PR_NUMBER: "${{ github.event.number }}"
          curl -X PUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d '{"merge_method": "merge"}' "https://api.github.com/repos/${{ github.repository }}/pulls/$GITHUB_PR_NUMBER/merge"
