name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout so job can access repo
        uses: actions/checkout@v3

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: utkarshtest/myjavaapp12
          path: myjavaapp12

      - name: install python
        uses: actions/setup-python@v5.0.0
        with: 
          python-version: 3.11

      - name: bandit install
        run: |
          pip install bandit
          pip install requests
          
      - name: run bandit command
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_PR_NUMBER: "${{ github.event.number }}"
        run: |
          ls
          # bandit -r . -ll -ii -f json --exit-zero -o bandit.json   
          # bandit -r . -ll -ii -f custom --msg-template "{severity}" --exit-zero -o out.txt # for the sake of time, I choose this method - I know their are some better options to pick.
          # python3 parser.py   

      # - name: Merge pull request
      #   env:
      #     GITHUB_PR_NUMBER: "${{ github.event.number }}"
      #   run: |
      #     curl -X PUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d '{"merge_method": "merge"}' "https://api.github.com/repos/${{ github.repository }}/pulls/$GITHUB_PR_NUMBER/merge"
      #     curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\":\"Successfull\"}" "https://api.github.com/repos/${{ github.repository }}/issues/$GITHUB_PR_NUMBER/comments"
      #     curl -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d '{"state":"closed"}' "https://api.github.com/repos/${{ github.repository }}/pulls/$GITHUB_PR_NUMBER"
      # - name: upload artifacts
      #   if: always()
      #   uses: actions/upload-artifact@v4.3.1
      #   with:
      #     name: Python_File
      #     path: bandit.json
        
