name: CI
on: [push]
#   pull_request:
#     branches: 
#       - main
#     types: [closed]

jobs:
  build2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout so job can access repo
        uses: actions/checkout@v3

      - name: install NodeJS
        uses: actions/setup-node@v4.0.2

      - name: install retire
        run: |
          git clone https://github.com/RetireJS/retire.js
          cd retire.js
          npm install -g retire
        
      - name: run retire 
        run: retire -v -c

      - name: ls
        run: ls

      # - name: upload artifacts
      #   if: always()
      #   uses: actions/upload-artifact@v4.3.1
      #   with:
      #     name: Retirejs Output file
      #     path: retire.json
